/* ~~~~~ Addresses ~~~~~ */
#define ADDRESS_PI 0x3A
#define ADDRESS_ARDUINO 0x01

/* ~~~~~ Payload IDs ~~~~~ */

#define PAYLOAD_ARDUINO_STARTUP_SUCCESS 0xA0
#define PAYLOAD_ARDUINO_STARTUP_FAIL 0xA1
#define PAYLOAD_PI_STARTUP_SUCCESS 0xA2
#define PAYLOAD_PI_STARTUP_FAIL 0xA3

#define PAYLOAD_ARDUINO_INIT_CONTACTS 0xB0
#define PAYLOAD_PI_MOVEMENT_INFO 0xB1
#define PAYLOAD_ARDUINO_TIME_POURED 0xB2
#define PAYLOAD_PI_MOVEMENT_COMPLETE 0xB3

#define PAYLOAD_BAD_PAYLOAD_ID 0xF0
#define PAYLOAD_BAD_CHECKSUM 0xF1

#define PAYLOAD_RESEND_MESSAGE 0xE0

/* ~~~~~ Payload Sizes ~~~~~ */

#define PAYLOAD_SIZE_EMPTY 0x00
#define PAYLOAD_SIZE_RESEND_MESSAGE 0x01
#define PAYLOAD_SIZE_ARDUINO_INIT_CONTACTS 0x01
#define PAYLOAD_SIZE_PI_MOVEMENT_INFO 0x21
#define PAYLOAD_SIZE_ARDUINO_TIME_POURED 0x20

/* ~~~~~ Other Sizes ~~~~~ */

#define HEADER_SIZE 3
#define FOOTER_SIZE 1
